# Generated by Django 4.0.1 on 2022-05-16 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_phone', models.IntegerField(blank=True, null=True)),
                ('employee_identity', models.IntegerField(blank=True, null=True)),
                ('employee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employee_salary', models.FloatField(blank=True, null=True)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companybranch', to='company.companybranch')),
            ],
        ),
    ]
