# Generated by Django 4.0.4 on 2022-05-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'الموظف', 'verbose_name_plural': 'الموظفين'},
        ),
    ]
