# Generated by Django 4.0.4 on 2022-05-19 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_company_address_and_more'),
        ('employee', '0003_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='branch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companybranches', to='company.companybranch', verbose_name='اسم الفرع'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ايميل الموظف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_identity',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم هوية الموظف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الموظف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='هاتف الموظف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_salary',
            field=models.FloatField(blank=True, null=True, verbose_name='راتب الموظف'),
        ),
    ]
