# Generated by Django 4.0.4 on 2022-05-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_options_alter_companybranch_options_and_more'),
        ('employee', '0003_alter_employee_options'),
        ('accounts', '0001_initial'),
        ('consumed', '0002_income_user_outcome_user_requiremtsbranch_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'دخل الفرع', 'verbose_name_plural': 'دخل الفروع'},
        ),
        migrations.AlterModelOptions(
            name='outcome',
            options={'verbose_name': 'مصاريف الفرع', 'verbose_name_plural': 'مصاريف الفروع'},
        ),
        migrations.AlterModelOptions(
            name='requiremtsbranch',
            options={'verbose_name': 'احتياجات الفرع', 'verbose_name_plural': 'احتياجات الفروع'},
        ),
        migrations.RenameField(
            model_name='outcome',
            old_name='employee',
            new_name='employee_outcome',
        ),
        migrations.AlterField(
            model_name='income',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='requiremtsbranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requiremtsbranches', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='requiremtsbranch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='company.companybranch', verbose_name='اسم الفرع'),
        ),
        migrations.AlterField(
            model_name='requiremtsbranch',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employee.employee', verbose_name='اسم الموظف'),
        ),
        migrations.AlterField(
            model_name='requiremtsbranch',
            name='things_need_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الطلب'),
        ),
        migrations.AlterField(
            model_name='requiremtsbranch',
            name='things_need_price',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الطلب'),
        ),
        migrations.AlterField(
            model_name='requiremtsbranch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='المستخدم'),
        ),
    ]
