# Generated by Django 4.0.4 on 2022-05-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comapny_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
