# Generated by Django 4.0.4 on 2022-05-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_comapny_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comapny_name',
        ),
    ]
