# Generated by Django 4.0.1 on 2022-05-16 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_phone', models.IntegerField(blank=True, null=True)),
                ('company_city', models.CharField(blank=True, max_length=200, null=True)),
                ('company_address', models.URLField(blank=True, null=True)),
                ('company_code', models.CharField(blank=True, max_length=255, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_phone', models.IntegerField(blank=True, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_city', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_address', models.URLField(blank=True, null=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.company')),
            ],
        ),
    ]
