# Generated by Django 4.0.4 on 2022-05-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_company_address'),
        ('company', '0003_alter_company_options_alter_companybranch_options_and_more'),
    ]

    operations = [
    ]
