# Generated by Django 4.0.4 on 2022-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_merge_20220517_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.URLField(blank=True, null=True, verbose_name='عنوان الشركة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم الفرع'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='شعار الشركة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم هاتف الشركة'),
        ),
    ]
