# Generated by Django 4.0.4 on 2022-05-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_options_alter_companybranch_options_and_more'),
        ('customercar', '0003_alter_carpart_options_alter_customercar_options_and_more'),
        ('invoice', '0002_remove_invoice_created_date_invoice_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'الفاتورة', 'verbose_name_plural': 'الفواتير'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchs', to='company.companybranch', verbose_name='اسم الفرع'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='carpart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carparts', to='customercar.carpart', verbose_name='قطع غيار السيارة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customercar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customercars', to='customercar.customercar', verbose_name='اسم مالك السيارة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_price',
            field=models.FloatField(blank=True, null=True, verbose_name='الضريبة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_after_tax',
            field=models.FloatField(blank=True, null=True, verbose_name='مبلغ الاجمالي بعد الضريبة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='مبلغ الاجمالي قبل الضريبة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='work_hand_price',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر صيانة'),
        ),
    ]
