# Generated by Django 4.0.4 on 2022-05-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_options_alter_companybranch_options_and_more'),
        ('employee', '0003_alter_employee_options'),
        ('accounts', '0001_initial'),
        ('customercar', '0002_carpart_user_customercar_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carpart',
            options={'verbose_name': 'قطع غيار السيارة', 'verbose_name_plural': 'قطع غيار السيارات'},
        ),
        migrations.AlterModelOptions(
            name='customercar',
            options={'verbose_name': 'سيارة العميل', 'verbose_name_plural': 'سيارات العملاء'},
        ),
        migrations.AlterField(
            model_name='carpart',
            name='customer_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customercar', to='customercar.customercar', verbose_name=' رقم السيارة العميل'),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='part_invoice',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=' ارفاق صورة الفواتير قطع الغيار'),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='part_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' اسم القطعة الغيار'),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='part_price',
            field=models.IntegerField(blank=True, null=True, verbose_name=' سعر قطعة الغيار'),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='customercar',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='company.companybranch', verbose_name='اسم الفرع'),
        ),
        migrations.AlterField(
            model_name='customercar',
            name='car_color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='لون السيارة'),
        ),
        migrations.AlterField(
            model_name='customercar',
            name='car_company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ماركت السيارة'),
        ),
        migrations.AlterField(
            model_name='customercar',
            name='car_plate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم اللوحة'),
        ),
        migrations.AlterField(
            model_name='customercar',
            name='car_ready',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='السيارة جاهزه للاستلام'),
        ),
        migrations.AlterField(
            model_name='customercar',
            name='car_under_process',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='السيارة في الصيانة'),
        ),
        migrations.AlterField(
            model_name='customercar',
            name='date_entery',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ استلام المركبة'),
        ),
        migrations.AlterField(
            model_name='customercar',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplyees', to='employee.employee', verbose_name='اسم الموظف'),
        ),
        migrations.AlterField(
            model_name='customercar',
            name='owner_car_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم مالك السيارة'),
        ),
        migrations.AlterField(
            model_name='customercar',
            name='owner_car_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم هاتف المالك'),
        ),
        migrations.AlterField(
            model_name='customercar',
            name='owner_identity',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم هوية المالك'),
        ),
        migrations.AlterField(
            model_name='customercar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='المستخدم'),
        ),
    ]
