# Generated by Django 4.0.4 on 2022-05-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercar', '0004_alter_carpart_user_alter_customercar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercar',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
