# Generated by Django 4.0.4 on 2022-05-21 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_company_address_and_more'),
        ('employee', '0004_alter_employee_branch_name_and_more'),
        ('customercar', '0005_customercar_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpart',
            name='part_name',
            field=models.CharField(default=1, max_length=255, verbose_name=' اسم القطعة الغيار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carpart',
            name='part_price',
            field=models.IntegerField(default=1, verbose_name=' سعر قطعة الغيار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customercar',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='company.companybranch', verbose_name='اسم الفرع'),
        ),
        migrations.AlterField(
            model_name='customercar',
            name='car_ready',
            field=models.BooleanField(default=False, verbose_name='السيارة جاهزه للاستلام'),
        ),
        migrations.AlterField(
            model_name='customercar',
            name='car_under_process',
            field=models.BooleanField(default=True, verbose_name='السيارة في الصيانة'),
        ),
        migrations.AlterField(
            model_name='customercar',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emplyees', to='employee.employee', verbose_name='اسم الموظف'),
        ),
        migrations.AlterField(
            model_name='customercar',
            name='owner_car_name',
            field=models.CharField(default=1, max_length=255, verbose_name='اسم مالك السيارة'),
            preserve_default=False,
        ),
    ]
