# Generated by Django 4.0.4 on 2022-05-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercar', '0006_alter_carpart_part_name_alter_carpart_part_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercar',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
